### ISSUE TITLE
Traefik forward authentication

### ISSUE THREAD

**Issue by ppoloskov** [tarent/loginsrv#132]
Is it possible to use Loginsrv as forward auth proxy with traefik (https://docs.traefik.io/configuration/entrypoints/#forward-authentication)?

**Comment by magikstm** [comment]
Did you try using loginsrv with Httpupstream?

Ref: https://github.com/tarent/loginsrv#httpupstream

**Comment by LinusT** [comment]
I believe what @ppoloskov (and I) are interested is the reverse of what you are referring to @magikstm. IE let traefik delegate the authentication to loginsrv.

Perhaps looking into this https://github.com/tarent/loginsrv#get-login could be the way forward?

Are there any examples for loginsrv as upstream authenticator for any proxy (not specifically traefik) that can be shared here?

ATM I do not have time to dig into this / setup a test environment hence the questions rather than an answer.

**Comment by g-w** [comment]
Hello @LinusT, 

the "GET /login" endpoint might not be a solution for your problem. But I think it could be easily turned into an endpoint that behaves as expected by the traefik middleware.  

A better solution would be to use the JWT tokens issued by loginsrv and check them either in a custom traefik middleware or in the services.

I will close this issue. If you want to  suggest any improvements, please reopen the issue! So that we can discuss your suggestions.
