### ISSUE TITLE
Update Google OAuth to use standard OpenID endpoints

### ISSUE THREAD

**Issue by tdorsey** [tarent/loginsrv#65]
Is there any interest in updating the google oauth provider to use google's OAuth endpoints instead of requiring the people API? I'll admit to having walked into this one face first, and it seems like others have as well (ref #59) Right now, the auth and token endpoints are hardcoded in the project. See https://developers.google.com/identity/protocols/OpenIDConnect#discovery. If there aren't objections, I'd be willing to submit a PR for it.

**Comment by smancke** [comment]
I was not aware of the differences of the api's. It looks like a good idea to change it, so a pull request is welcome! But we have to ensure, that the existing installations of users do not break.
So it would be good to test first, that no config actions are required on the google side for our users.

**Comment by dobegor** [comment]
@smancke is there anything that needs to be updated regarding Plus API Shutdown?
I.e. `plus.people.get` method is deprecated now and will be removed.

**Comment by smancke** [comment]
@dobegor Yes, the following call has to use another api.
https://github.com/tarent/loginsrv/blob/23bd16e1ae8f7c8b8442b0119e7d4a25a7ae9cf9/oauth2/google.go#L37
I have put this on schedule to do it at least in the second week of January, because I'm also using google auth in production. If somebody want's to do it faster, feel free to submit a pr :)
